### PR TITLE
Update stable to 3.32.0

### PR DESCRIPTION
**Pull request by t-chaik**

### CODE REVIEW

**Comment by jbicha** [comment]
At a minimum, you'll need the rename-icon rule update from the `beta` branch.

**Comment by t-chaik** [comment]
I had no idea there was a `beta` branch, nice! Makes we wonder what version it should be updated to now: stable until future 3.33.90?

**Comment by jbicha** [comment]
See https://blogs.gnome.org/alexl/2019/02/19/changes-in-flathub-land/ if you haven't already (it's the announcement for Flathub betas). GNOME Software 3.32 allows easy switching between the beta and stable Flatpak channels.

I think it makes sense for the beta channel to match the stable channel for now.

Snap has 4 default channels which makes it a bit easier to know where to put things (stable, candidate, beta, edge). And you only have one channel installed at a time. And you can easily promote things from one channel to another so it's really easy to keep the beta and stable channels at the same version if you want.

Or you could have the beta channel be a "nighly" build from the stable git branch, but that sounds like a lot of work until you've automated it. (That's what we do for the gedit candidate channel snap.)

**Comment by t-chaik** [comment]
A nightly build of the stable git branch would be nice, but not sure how Flathub would help us doing that, the buildbot instance does allow periodic builds at the moment, does it?

**Pull request merged**
