### PR TITLE
update app and runtime to 3.38 

### PR DESCRIPTION
**Pull request by Lctrs**

### CODE REVIEW

**Comment by swilmet** [comment]
Thanks for your pull request.

Tepl no longer depends on uchardet, so that dependency can be removed from the Flatpak manifest.

**Comment by swilmet** [comment]
If not already done, you can take a look at the upstream Flatpak manifest here: \
https://gitlab.gnome.org/GNOME/gedit/-/blob/master/build-aux/flatpak/org.gnome.gedit.yml

**Comment by Lctrs** [comment]
@swilmet Done.

**Comment by swilmet** [comment]
Thanks, merged!

**Pull request merged**
